# This is a basic workflow to help you get started with Actions

name: Release Binaries

# Controls when the action will run. 
on:
  # Triggers the workflow on push events but only for tags
  push:
    tags:
      - 'v*.*.*'
    
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          submodules: 'true'
          
      # Used for conjure-typescript
      - uses: actions/setup-node@v2
        with:
          node-version: '15'
          
      # Used for conjure-typescript
      - name: Install yarn
        run: npm i -g yarn

      - name: Build conjure
        run: |
          cd conjure
          ./gradlew build --no-daemon

      - name: Build conjure-python
        run: |
          cd conjure-python
          ./gradlew build --no-daemon

      - name: Build conjure-postman
        run: |
          cd conjure-postman
          ./gradlew build --no-daemon
          
      - name: Build conjure-typescript
        run: |
          cd conjure-typescript
          yarn
          yarn build

      - name: Compile release body
        run: |
          echo '| Binary | Version |' > release.txt
          echo '| :-- | --: |' >> release.txt
          echo "| Conjure | $(cd conjure && git describe --tags HEAD) |" >> release.txt
          echo "| Conjure Python | $(cd conjure-python && git describe --tags HEAD) |" >> release.txt
          echo "| Conjure Typescript | $(cd conjure-typescript && git describe --tags HEAD) |" >> release.txt
          echo "| Conjure Postman | $(cd conjure-postman && git describe --tags HEAD) |" >> release.txt

      - name: GH Release
        uses: softprops/action-gh-release@v0.1.5
        if: startsWith(github.ref, 'refs/tags/')
        with:
          body_path: release.txt
          files: |
            conjure/conjure/build/distributions/conjure.tgz
            conjure/conjure/build/distributions/conjure.zip
            conjure-python/conjure-python/build/distributions/conjure-python.tgz
            conjure-python/conjure-python/build/distributions/conjure-python.zip
            conjure-postman/conjure-postman/build/distributions/conjure-postman.tgz
            conjure-postman/conjure-postman/build/distributions/conjure-postman.zip
            conjure-typescript/dist/bin/conjure-typescript
            conjure-typescript/dist/bin/conjure-typescript.bat
