# This is a basic workflow to help you get started with Actions

name: Release Binaries

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          submodules: 'true'

      - name: Build conjure
        run: |
          cd conjure
          ./gradlew build

      - name: Build conjure-python
        run: |
          cd conjure-python
          ./gradlew build

      - name: Build conjure-postman
        run: |
          cd conjure-postman
          ./gradlew build

      - name: GH Release
        uses: softprops/action-gh-release@v0.1.5
        with:
          files: |
            conjure/conjure/build/distributions/conjure.tgz
            conjure/conjure/build/distributions/conjure.zip
            conjure-python/conjure-python/build/distributions/conjure-python.tgz
            conjure-python/conjure-python/build/distributions/conjure-python.zip
            conjure-postman/conjure-postman/build/distributions/conjure-postman.tgz
            conjure-postman/conjure-postman/build/distributions/conjure-postman.zip
