# This is a basic workflow to help you get started with Actions

name: Release Binaries

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
    
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Used as the release name
      - name: set release name
        run: echo "release_name=auto-release-$(date +'%Y-%m-%dT%H:%M:%S')" >> $GITHUB_ENV

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          submodules: 'true'
          
      # Used for conjure-typescript
      - uses: actions/setup-node@v2
        with:
          node-version: '15'
          
      # Used for conjure-typescript
      - name: Install yarn
        run: npm i -g yarn

      - name: Build conjure
        run: |
          cd conjure
          ./gradlew build --no-daemon

      - name: Build conjure-python
        run: |
          cd conjure-python
          ./gradlew build --no-daemon

      - name: Build conjure-postman
        run: |
          cd conjure-postman
          ./gradlew build --no-daemon
          
      - name: Build conjure-typescript
        run: |
          cd conjure-typescript
          yarn
          yarn build

      - name: Compile release body
        run: |
          echo '| Binary | Version |' > release.txt
          echo '| :-- | --: |' >> release.txt
          echo "| Conjure | $(cd conjure && git describe --tags HEAD) |" >> release.txt
          echo "| Conjure Python | $(cd conjure-python && git describe --tags HEAD) |" >> release.txt
          echo "| Conjure Typescript | $(cd conjure-typescript && git describe --tags HEAD) |" >> release.txt
          echo "| Conjure Postman | $(cd conjure-postman && git describe --tags HEAD) |" >> release.txt

      - name: GH Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.release_name }}
          body_path: release.txt
          files: |
            conjure/conjure/build/distributions/conjure.tgz
            conjure/conjure/build/distributions/conjure.zip
            conjure-python/conjure-python/build/distributions/conjure-python.tgz
            conjure-python/conjure-python/build/distributions/conjure-python.zip
            conjure-postman/conjure-postman/build/distributions/conjure-postman.tgz
            conjure-postman/conjure-postman/build/distributions/conjure-postman.zip
            conjure-typescript/dist/bin/conjure-typescript
            conjure-typescript/dist/bin/conjure-typescript.bat
